# Generated by Django 4.2.6 on 2023-10-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('price_monthly', models.CharField(blank=True, max_length=30, null=True)),
                ('price_yearly', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, default='ایمیل اختصاصی', max_length=30, null=True)),
                ('frame', models.CharField(blank=True, default='قالب', max_length=30, null=True)),
                ('prodc', models.CharField(blank=True, default='محصول', max_length=30, null=True)),
                ('imgforpro', models.CharField(blank=True, default='تصویر برای هر محصول', max_length=30, null=True)),
                ('Bandwidth', models.CharField(blank=True, default='پهنای باند', max_length=30, null=True)),
                ('support', models.CharField(blank=True, default='پشتیبانی 24 ساعته', max_length=30, null=True)),
            ],
        ),
    ]
